### ISSUE TITLE
does not work

### ISSUE THREAD

**Issue by filly82** [ali2236/loader#1]
`Loader<String>(
              load: () async {
                return "Hello World";
              },
              builder: (context, value) {
                return Text(value);
              },
            )`

results into

`
I/flutter (13848): The following assertion was thrown building Loader<String>(dirty, state: _LoaderState#2fafb):
I/flutter (13848): type '(BuildContext, String) => Text' is not a subtype of type '(BuildContext, dynamic) => Widget'
`

**Comment by ali2236** [comment]
fixed it in 0.3.3
